### ISSUE TITLE
Navbar icons are light blue when on my own profile page. :D

### ISSUE THREAD

**Issue by BKFighter** [LilCoders/Bugs#1]
Navbar icons are light blue when on my own profile page. :D

**Comment by CosmicWebServices** [comment]
yeah same here but we know why it happens

**Comment by CosmicWebServices** [comment]
Also off-topic gitter is blocked on my school wifi so I cannot help out on gitter until I come home. Maybe I can contact another way...

**Comment by CosmicWebServices** [comment]
@HittmanA ^^

**Comment by HittmanA** [comment]
I will work on fixing

**Comment by CosmicWebServices** [comment]
Hi! I am about to leave school

**Comment by CosmicWebServices** [comment]
Soooo what did u do today?

**Comment by CosmicWebServices** [comment]
@HittmanA

**Comment by CosmicWebServices** [comment]
All we have to do now is remove bootstrap from ALL pages

**Comment by CosmicWebServices** [comment]
Fixed
