### ISSUE TITLE
Security: Infinity loops crash chrome browser had to use task manager to close tab.

### ISSUE THREAD

**Issue by CosmicWebServices** [LilCoders/Bugs#9]
Read above ^^^

**Comment by HittmanA** [comment]
?

**Comment by CosmicWebServices** [comment]
Infiniti loops crash crome @HittmanA

**Comment by HittmanA** [comment]
What causes them?

**Comment by CosmicWebServices** [comment]
If you do it on purpose

**Comment by HittmanA** [comment]
Tell me what you did to cause it!!!!!!! Telling me it happens and not explaining how is not helpful!

**Comment by CosmicWebServices** [comment]
Sorry here it is:
```
for (var i=1;i<5;i--) {
console.log(i)
}
```

**Comment by HittmanA** [comment]
Hence why chrome sucks, Safari doesn't crash when you do that. I dont think we can prevent users from using that code. Just make a rule saying any code designed to crash a browser will be removed and the user who made it will be banned.

**Comment by CosmicWebServices** [comment]
OK

**Comment by CosmicWebServices** [comment]
While you are here @HittmanA We need to get LilCoders done ASAP 16 days till release and it would be great if we are done the important stuff 1 week before LilCoders is released

**Comment by JordanB-1337** [comment]
That's what I'm trying to do as well (with the forums)

**Comment by CosmicWebServices** [comment]
OK
